[toolchain]
anchor_version = "0.29.0"
rust_version = "nightly"
[features]
resolution = true
skip-lint = false

[programs.devnet]
investment_program = "Mh9eszZZsLKqd17YTTy1rKMSshKY4aqBaNPGBG8x5db"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
